# fly.toml app configuration file generated for screen-to-deck on 2024-07-02T07:45:00Z
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "screen-to-deck"
primary_region = "cdg" # Paris, proche de tes utilisateurs européens
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  dockerfile = "Dockerfile.saas"

[deploy]
  release_command = "npm run db:migrate"
  
[[services]]
  protocol = "tcp"
  internal_port = 3001
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 80

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
    tls_skip_verify = false

    [services.http_checks.headers]
      X-Forwarded-Proto = "https"

[env]
  NODE_ENV = "production"
  PORT = "3001"
  
# VM resources
[compute]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

# Auto-scaling configuration
[[http_service]]
  internal_port = 3001
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 80

# Redis cache pour rate limiting
[[redis]]
  name = "screen-to-deck-redis"

# Volume pour logs persistants
[[mounts]]
  source = "screen_to_deck_logs"
  destination = "/app/logs"
  initial_size = "1gb"

# Scaling configuration
[scaling]
  min_machines_running = 1
  max_machines_running = 10

[[metrics]]
  port = 9091
  path = "/metrics" 