# fly.toml app configuration file generated for screen-to-deck on 2024-07-02T07:45:00Z
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "screen-to-deck"
primary_region = "cdg"  # Paris pour l'Europe
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  dockerfile = "Dockerfile.saas"

[env]
  NODE_ENV = "production"
  PORT = "3001"
  
# VM resources
[compute]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 4096

# Auto-scaling configuration
[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    hard_limit = 1000
    soft_limit = 800

# Redis cache pour rate limiting
[[redis]]
  name = "screen-to-deck-redis"

# Volume pour logs persistants
[[mounts]]
  source = "screen_to_deck_logs"
  destination = "/app/logs"
  initial_size = "1gb"

# Scaling configuration
[scaling]
  min_machines_running = 1
  max_machines_running = 10

[[metrics]]
  port = 9091
  path = "/metrics"

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/api/health"

[deploy]
  release_command = "npm run build"

[[statics]]
  guest_path = "/app/client/dist"
  url_prefix = "/" 