name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies (workspace)
        run: |
          npm install

      - name: Lint (server)
        run: npm run lint:server

      - name: Lint (client)
        run: npm run lint:client

      - name: Type check (client)
        run: npm --workspace client run type-check

      - name: Build (server)
        run: npm run build:server

      - name: Build (client)
        run: npm run build:client

      # Note: Tests are being stabilized; enable when suites are ready
      # - name: Test (server)
      #   run: npm --workspace server test --if-present -- --passWithNoTests
      # - name: Test (client)
      #   run: npm --workspace client test --if-present

  security-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps (root only)
        run: npm install --no-audit --no-fund

      - name: NPM Audit (non-blocking)
        run: |
          set +e
          npm audit --audit-level=high || true
