name: Build and Push Bot Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'discord-bot/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./discord-bot
          push: true
          tags: ghcr.io/${{ github.repository }}/discord-bot:latest
          cache-from: type=gha,scope=discord-bot
          cache-to: type=gha,mode=max,scope=discord-bot 